name: debug
seed: 1337

# ----------
# dataset
# ----------
dataset: imagenet
# ----------
# model
# ----------
model: resnet50
criterion: cross_entropy
# ----------
# optim
# ----------
optimizer: SGD
lr: 0.1
scheduler: cosine
warmup: true
# ----------
# performance
# ----------
max_epochs: 100
batch_size: 256
num_workers: 4
