name: debug
seed: 1337

# ----------
# dataset
# ----------
dataset: mnist
# ----------
# model
# ----------
model: toy_conv
criterion: cross_entropy
# ----------
# optim
# ----------
optimizer: Adam
lr: 0.1
# ----------
# performance
# ----------
batch_size: 64
num_workers: 4
